import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import Header from "./ui/components/nav";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["cyrillic"], weight: "300" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} `} style={{}}>
        <Header />

        {children}
      </body>
    </html>
  );
}
